import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import { Event, type IEvent } from "@/database";

type RouteParams = {
    params: {
        slug?: string;
    };
};

function normalizeSlug(rawSlug: string): string {
    return rawSlug.trim().toLowerCase();
}

function isValidSlug(slug: string): boolean {
    // Matches the slug shape generated by the Event model.
    return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);
}

export async function GET(_request: Request, { params }: RouteParams) {
    try {
        const rawSlug = params?.slug;

        if (!rawSlug) {
            return NextResponse.json(
                { message: "Event fetching failed", error: "Slug is required" },
                { status: 400 }
            );
        }

        const slug = normalizeSlug(rawSlug);

        if (!isValidSlug(slug)) {
            return NextResponse.json(
                { message: "Event fetching failed", error: "Slug is invalid" },
                { status: 400 }
            );
        }

        await connectDB();

        const event = await Event.findOne({ slug }).lean<IEvent | null>();

        if (!event) {
            return NextResponse.json(
                { message: "Event fetching failed", error: "Event not found" },
                { status: 404 }
            );
        }

        return NextResponse.json(
            { message: "Event fetched successfully", event },
            { status: 200 }
        );
    } catch (error: unknown) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return NextResponse.json(
            { message: "Event fetching failed", error: message },
            { status: 500 }
        );
    }
}
